from PyQt5 import QtCore, QtGui, QtWidgets


class AddAnimeWindow(object):

    def main_ui(self, add_anime_window):
        add_anime_window.resize(600, 200)
        add_anime_window.setMaximumSize(QtCore.QSize(600, 200))
        self.centralwidget = QtWidgets.QWidget(add_anime_window)
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 200))
        self.centralwidget.setStyleSheet("background-color: rgb(52, 52, 52)")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.score_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.score_dropdown.setMinimumSize(QtCore.QSize(0, 40))
        self.score_dropdown.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.score_dropdown.addItem("")
        self.score_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.score_dropdown, 2, 1, 1, 1)
        self.anime_name = QtWidgets.QLabel(self.centralwidget)
        self.anime_name.setMinimumSize(QtCore.QSize(0, 40))
        self.anime_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 20pt \"Segoe UI Variable Display Semib\";")
        self.anime_name.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.anime_name, 0, 0, 1, 4)
        self.score_lbl = QtWidgets.QLabel(self.centralwidget)
        self.score_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.score_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 13pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout_2.addWidget(self.score_lbl, 1, 1, 1, 1)
        self.episodes_lbl = QtWidgets.QLabel(self.centralwidget)
        self.episodes_lbl.setMinimumSize(QtCore.QSize(0, 15))
        self.episodes_lbl.setMaximumSize(QtCore.QSize(16777215, 15))
        self.episodes_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 13pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout_2.addWidget(self.episodes_lbl, 1, 2, 1, 1)
        self.status_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.status_dropdown.setMinimumSize(QtCore.QSize(160, 40))
        self.status_dropdown.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.status_dropdown.addItem("")
        self.status_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.status_dropdown, 2, 0, 1, 1)
        self.status_lbl = QtWidgets.QLabel(self.centralwidget)
        self.status_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.status_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 13pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout_2.addWidget(self.status_lbl, 1, 0, 1, 1)
        self.episodes_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.episodes_dropdown.setMinimumSize(QtCore.QSize(0, 40))
        self.episodes_dropdown.setMaximumSize(QtCore.QSize(16777215, 60))
        self.episodes_dropdown.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.episodes_dropdown.addItem("")
        self.episodes_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.episodes_dropdown, 2, 2, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setMinimumSize(QtCore.QSize(0, 70))
        self.save_btn.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.gridLayout_2.addWidget(self.save_btn, 1, 3, 2, 1)
        add_anime_window.setCentralWidget(self.centralwidget)
        self.retranslateUi(add_anime_window)
        QtCore.QMetaObject.connectSlotsByName(add_anime_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.score_dropdown.setItemText(0, _translate("MainWindow", "Новый элемент"))
        self.score_dropdown.setItemText(1, _translate("MainWindow", "Новый элемент"))
        self.anime_name.setText(_translate("MainWindow", "ANIME NAME"))
        self.score_lbl.setText(_translate("MainWindow", "Your score"))
        self.episodes_lbl.setText(_translate("MainWindow", "Episodes watched"))
        self.status_dropdown.setItemText(0, _translate("MainWindow", "Новый элемент"))
        self.status_dropdown.setItemText(1, _translate("MainWindow", "Новый элемент"))
        self.status_lbl.setText(_translate("MainWindow", "Status"))
        self.episodes_dropdown.setItemText(0, _translate("MainWindow", "Новый элемент"))
        self.episodes_dropdown.setItemText(1, _translate("MainWindow", "Новый элемент"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
