from PyQt5 import QtCore, QtGui, QtWidgets


class AddMangaWindow(object):
    def main_ui(self, add_manga_window):
        add_manga_window.resize(800, 200)
        add_manga_window.setMaximumSize(QtCore.QSize(800, 200))
        self.centralwidget = QtWidgets.QWidget(add_manga_window)
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 200))
        self.centralwidget.setStyleSheet("background-color: rgb(52, 52, 52)")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.score_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.score_dropdown.setMinimumSize(QtCore.QSize(0, 40))
        self.score_dropdown.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.score_dropdown.addItem("")
        self.score_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.score_dropdown, 2, 1, 1, 1)
        self.manga_name = QtWidgets.QLabel(self.centralwidget)
        self.manga_name.setMinimumSize(QtCore.QSize(0, 40))
        self.manga_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 20pt \"Segoe UI Variable Display Semib\";")
        self.manga_name.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.manga_name, 0, 0, 1, 5)
        self.score_lbl = QtWidgets.QLabel(self.centralwidget)
        self.score_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.score_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 13pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout_2.addWidget(self.score_lbl, 1, 1, 1, 1)
        self.chapters_lbl = QtWidgets.QLabel(self.centralwidget)
        self.chapters_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.chapters_lbl.setMaximumSize(QtCore.QSize(16777215, 15))
        self.chapters_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 13pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout_2.addWidget(self.chapters_lbl, 1, 2, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setMinimumSize(QtCore.QSize(0, 70))
        self.save_btn.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.gridLayout_2.addWidget(self.save_btn, 1, 4, 2, 1)
        self.status_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.status_dropdown.setMinimumSize(QtCore.QSize(160, 40))
        self.status_dropdown.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.status_dropdown.addItem("")
        self.status_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.status_dropdown, 2, 0, 1, 1)
        self.status_lbl = QtWidgets.QLabel(self.centralwidget)
        self.status_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.status_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 13pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout_2.addWidget(self.status_lbl, 1, 0, 1, 1)
        self.chapters_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.chapters_dropdown.setMinimumSize(QtCore.QSize(0, 40))
        self.chapters_dropdown.setMaximumSize(QtCore.QSize(16777215, 60))
        self.chapters_dropdown.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.chapters_dropdown.addItem("")
        self.chapters_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.chapters_dropdown, 2, 2, 1, 1)
        self.volumes_lbl = QtWidgets.QLabel(self.centralwidget)
        self.volumes_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.volumes_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 13pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout_2.addWidget(self.volumes_lbl, 1, 3, 1, 1)
        self.volumes_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.volumes_dropdown.setMinimumSize(QtCore.QSize(0, 40))
        self.volumes_dropdown.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.volumes_dropdown.addItem("")
        self.volumes_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.volumes_dropdown, 2, 3, 1, 1)
        add_manga_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(add_manga_window)
        QtCore.QMetaObject.connectSlotsByName(add_manga_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.score_dropdown.setItemText(0, _translate("MainWindow", "Новый элемент"))
        self.score_dropdown.setItemText(1, _translate("MainWindow", "Новый элемент"))
        self.manga_name.setText(_translate("MainWindow", "MANGA NAME"))
        self.score_lbl.setText(_translate("MainWindow", "Your score"))
        self.chapters_lbl.setText(_translate("MainWindow", "Chapters read"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.status_dropdown.setItemText(0, _translate("MainWindow", "Новый элемент"))
        self.status_dropdown.setItemText(1, _translate("MainWindow", "Новый элемент"))
        self.status_lbl.setText(_translate("MainWindow", "Status"))
        self.chapters_dropdown.setItemText(0, _translate("MainWindow", "Новый элемент"))
        self.chapters_dropdown.setItemText(1, _translate("MainWindow", "Новый элемент"))
        self.volumes_lbl.setText(_translate("MainWindow", "Volumes read"))
        self.volumes_dropdown.setItemText(0, _translate("MainWindow", "Новый элемент"))
        self.volumes_dropdown.setItemText(1, _translate("MainWindow", "Новый элемент"))
