from PyQt5 import QtCore, QtGui, QtWidgets
from CharacterWindow import CharacterWindow
from EpisodeWindow import EpisodeWindow
from AddAnimeToList import AddAnimeWindow


class AnimeInfo(object):
    def __init__(self, parent):
        self.parent_window = parent

    def main_ui(self, anime_info):
        anime_info.resize(800, 575)
        anime_info.setMinimumSize(QtCore.QSize(800, 575))
        anime_info.setMaximumSize(QtCore.QSize(800, 575))
        self.centralwidget = QtWidgets.QWidget(anime_info)
        self.bg = QtWidgets.QFrame(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 800, 575))
        self.bg.setStyleSheet("background-color: rgb(52, 52, 52)")
        self.bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image = QtWidgets.QLabel(self.bg)
        self.image.setGeometry(QtCore.QRect(20, 20, 150, 210))
        self.image.setPixmap(QtGui.QPixmap("./1.jpg"))
        self.image.setScaledContents(True)
        self.anime_name = QtWidgets.QLabel(self.bg)
        self.anime_name.setGeometry(QtCore.QRect(175, 20, 601, 41))
        self.anime_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 14pt Segoe UI Variable Display Semib;")
        self.en_title = QtWidgets.QLabel(self.bg)
        self.en_title.setGeometry(QtCore.QRect(175, 60, 101, 21))
        self.en_title.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.en_name = QtWidgets.QLabel(self.bg)
        self.en_name.setGeometry(QtCore.QRect(300, 60, 371, 21))
        self.en_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.jp_title = QtWidgets.QLabel(self.bg)
        self.jp_title.setGeometry(QtCore.QRect(175, 90, 111, 21))
        self.jp_title.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.jp_name = QtWidgets.QLabel(self.bg)
        self.jp_name.setGeometry(QtCore.QRect(300, 90, 371, 21))
        self.jp_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.score = QtWidgets.QLabel(self.bg)
        self.score.setGeometry(QtCore.QRect(710, 60, 81, 21))
        self.score.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.score_number = QtWidgets.QLabel(self.bg)
        self.score_number.setGeometry(QtCore.QRect(710, 80, 51, 21))
        self.score_number.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.score_number.setAlignment(QtCore.Qt.AlignCenter)
        self.show_name = QtWidgets.QLabel(self.bg)
        self.show_name.setGeometry(QtCore.QRect(20, 240, 111, 21))
        self.show_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.type_name = QtWidgets.QLabel(self.bg)
        self.type_name.setGeometry(QtCore.QRect(145, 240, 171, 21))
        self.type_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.status_name = QtWidgets.QLabel(self.bg)
        self.status_name.setGeometry(QtCore.QRect(145, 270, 171, 21))
        self.status_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.current_status = QtWidgets.QLabel(self.bg)
        self.current_status.setGeometry(QtCore.QRect(20, 270, 111, 21))
        self.current_status.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.aired_from_date = QtWidgets.QLabel(self.bg)
        self.aired_from_date.setGeometry(QtCore.QRect(145, 300, 171, 21))
        self.aired_from_date.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.aired_from = QtWidgets.QLabel(self.bg)
        self.aired_from.setGeometry(QtCore.QRect(20, 300, 111, 21))
        self.aired_from.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.aired_to_date = QtWidgets.QLabel(self.bg)
        self.aired_to_date.setGeometry(QtCore.QRect(145, 330, 171, 21))
        self.aired_to_date.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.aired_to = QtWidgets.QLabel(self.bg)
        self.aired_to.setGeometry(QtCore.QRect(20, 330, 111, 21))
        self.aired_to.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.num_episodes = QtWidgets.QLabel(self.bg)
        self.num_episodes.setGeometry(QtCore.QRect(20, 360, 111, 41))
        self.num_episodes.setAcceptDrops(False)
        self.num_episodes.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.num_episodes.setScaledContents(False)
        self.num_episodes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.num_episodes.setWordWrap(True)
        self.num_eps = QtWidgets.QLabel(self.bg)
        self.num_eps.setGeometry(QtCore.QRect(145, 360, 111, 41))
        self.num_eps.setAcceptDrops(False)
        self.num_eps.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.num_eps.setScaledContents(False)
        self.num_eps.setWordWrap(True)
        self.episode_duration = QtWidgets.QLabel(self.bg)
        self.episode_duration.setGeometry(QtCore.QRect(20, 410, 111, 41))
        self.episode_duration.setAcceptDrops(False)
        self.episode_duration.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.episode_duration.setScaledContents(False)
        self.episode_duration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.episode_duration.setWordWrap(True)
        self.dur_time = QtWidgets.QLabel(self.bg)
        self.dur_time.setGeometry(QtCore.QRect(145, 410, 111, 41))
        self.dur_time.setAcceptDrops(False)
        self.dur_time.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.dur_time.setScaledContents(False)
        self.dur_time.setWordWrap(True)
        self.genres = QtWidgets.QLabel(self.bg)
        self.genres.setGeometry(QtCore.QRect(300, 240, 111, 31))
        self.genres.setAcceptDrops(False)
        self.genres.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.genres.setScaledContents(False)
        self.genres.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.genres.setWordWrap(True)
        self.genres_names = QtWidgets.QLabel(self.bg)
        self.genres_names.setGeometry(QtCore.QRect(300, 280, 161, 91))
        self.genres_names.setAcceptDrops(False)
        self.genres_names.setStyleSheet("color: rgb(255, 255, 255); font: 63 10pt Segoe UI Variable Display Semib;")
        self.genres_names.setScaledContents(False)
        self.genres_names.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.genres_names.setWordWrap(True)
        self.themes = QtWidgets.QLabel(self.bg)
        self.themes.setGeometry(QtCore.QRect(480, 240, 111, 31))
        self.themes.setAcceptDrops(False)
        self.themes.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.themes.setScaledContents(False)
        self.themes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.themes.setWordWrap(True)
        self.theme_names = QtWidgets.QLabel(self.bg)
        self.theme_names.setGeometry(QtCore.QRect(480, 280, 171, 91))
        self.theme_names.setAcceptDrops(False)
        self.theme_names.setStyleSheet("color: rgb(255, 255, 255); font: 63 10pt Segoe UI Variable Display Semib;")
        self.theme_names.setScaledContents(False)
        self.theme_names.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.theme_names.setWordWrap(True)
        self.synopsis = QtWidgets.QLabel(self.bg)
        self.synopsis.setGeometry(QtCore.QRect(175, 120, 71, 21))
        self.synopsis.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.synopsis_text = QtWidgets.QLabel(self.bg)
        self.synopsis_text.setGeometry(QtCore.QRect(175, 140, 521, 91))
        self.synopsis_text.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.synopsis_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.synopsis_text.setWordWrap(True)
        self.add_to_list = QtWidgets.QPushButton(self.bg)
        self.add_to_list.setGeometry(QtCore.QRect(20, 510, 441, 51))
        self.add_to_list.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\"; background-color: rgb(27, 27, 45);")
        self.back_btn = QtWidgets.QPushButton(self.bg)
        self.back_btn.setGeometry(QtCore.QRect(640, 510, 141, 51))
        self.back_btn.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\"; background-color: rgb(27, 27, 45);")
        self.anime_characters = QtWidgets.QPushButton(self.bg)
        self.anime_characters.setGeometry(QtCore.QRect(300, 400, 161, 51))
        self.anime_characters.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\"; background-color: rgb(27, 27, 45);")
        self.broadcast_time = QtWidgets.QLabel(self.bg)
        self.broadcast_time.setGeometry(QtCore.QRect(20, 460, 111, 21))
        self.broadcast_time.setAcceptDrops(False)
        self.broadcast_time.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.broadcast_time.setScaledContents(False)
        self.broadcast_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.broadcast_time.setWordWrap(True)
        self.cast_time = QtWidgets.QLabel(self.bg)
        self.cast_time.setGeometry(QtCore.QRect(145, 460, 151, 21))
        self.cast_time.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt Segoe UI Variable Display Semib;")
        self.cast_time.setScaledContents(False)
        self.cast_time.setWordWrap(True)
        self.episodes = QtWidgets.QPushButton(self.bg)
        self.episodes.setGeometry(QtCore.QRect(480, 400, 161, 51))
        self.episodes.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt "
                                    "\"Segoe UI Variable Display Semib\"; background-color: rgb(27, 27, 45);")
        self.anime_characters.clicked.connect(self.character_info)
        self.episodes.clicked.connect(self.episode_info)
        self.add_to_list.clicked.connect(self.add_list)
        self.back_btn.clicked.connect(lambda: None)
        anime_info.setCentralWidget(self.centralwidget)
        self.load_ui(anime_info)
        QtCore.QMetaObject.connectSlotsByName(anime_info)

    def character_info(self):
        self.char_info = QtWidgets.QMainWindow()
        self.char_info_ui = CharacterWindow()
        self.char_info_ui.main_ui(self.char_info)
        self.char_info.show()

    def episode_info(self):
        self.episode_info = QtWidgets.QMainWindow()
        self.episode_info_ui = EpisodeWindow()
        self.episode_info_ui.main_ui(self.episode_info)
        self.episode_info.show()

    def add_list(self):
        self.add_to_list_window = QtWidgets.QMainWindow()
        self.add_to_list_ui = AddAnimeWindow()
        self.add_to_list_ui.main_ui(self.add_to_list_window)
        self.add_to_list_window.show()

    def back(self):
        pass

    def load_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.anime_name.setText(_translate("MainWindow", "ANIME NAME"))
        self.en_title.setText(_translate("MainWindow", "English Name:"))
        self.en_name.setText(_translate("MainWindow", "en_name"))
        self.jp_title.setText(_translate("MainWindow", "Japanese Name:"))
        self.jp_name.setText(_translate("MainWindow", "jp_name"))
        self.score.setText(_translate("MainWindow", "SCORE"))
        self.score_number.setText(_translate("MainWindow", "7"))
        self.show_name.setText(_translate("MainWindow", "Show type"))
        self.type_name.setText(_translate("MainWindow", "show_type"))
        self.status_name.setText(_translate("MainWindow", "status_name"))
        self.current_status.setText(_translate("MainWindow", "Current status"))
        self.aired_from_date.setText(_translate("MainWindow", "aired_from"))
        self.aired_from.setText(_translate("MainWindow", "Aired from"))
        self.aired_to_date.setText(_translate("MainWindow", "aired_to"))
        self.aired_to.setText(_translate("MainWindow", "Aired to"))
        self.num_episodes.setText(_translate("MainWindow", "Number of episodes"))
        self.num_eps.setText(_translate("MainWindow", "number"))
        self.episode_duration.setText(_translate("MainWindow", "Episode duration"))
        self.dur_time.setText(_translate("MainWindow", "duration"))
        self.genres.setText(_translate("MainWindow", "Genres"))
        self.genres_names.setText(_translate("MainWindow", "genres_names"))
        self.themes.setText(_translate("MainWindow", "Themes"))
        self.theme_names.setText(_translate("MainWindow", "theme_names"))
        self.synopsis.setText(_translate("MainWindow", "Synopsis"))
        self.synopsis_text.setText(_translate("MainWindow", "synopsis_text"))
        self.add_to_list.setText(_translate("MainWindow", "Add to my list"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.anime_characters.setText(_translate("MainWindow", "Anime characters"))
        self.broadcast_time.setText(_translate("MainWindow", "Broadcast time"))
        self.cast_time.setText(_translate("MainWindow", "time"))
        self.episodes.setText(_translate("MainWindow", "Episodes"))

