from PyQt5 import QtCore, QtGui, QtWidgets


class CharacterWindow(object):
    def main_ui(self, character_window):
        character_window.resize(640, 480)
        character_window.setMaximumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(character_window)
        self.centralwidget.setStyleSheet("background-color: rgb(52, 52, 52)")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.en_name = QtWidgets.QLabel(self.centralwidget)
        self.en_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.en_name, 3, 2, 1, 1)
        self.role = QtWidgets.QLabel(self.centralwidget)
        self.role.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.role, 1, 2, 1, 1)
        self.role_lbl = QtWidgets.QLabel(self.centralwidget)
        self.role_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.role_lbl, 1, 1, 1, 1)
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.name, 0, 2, 1, 1)
        self.name_lbl = QtWidgets.QLabel(self.centralwidget)
        self.name_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.name_lbl, 0, 1, 1, 1)
        self.en_voice_actor = QtWidgets.QLabel(self.centralwidget)
        self.en_voice_actor.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.en_voice_actor, 3, 1, 1, 1)
        self.jp_voice_actor = QtWidgets.QLabel(self.centralwidget)
        self.jp_voice_actor.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.jp_voice_actor, 2, 1, 1, 1)
        self.jp_name = QtWidgets.QLabel(self.centralwidget)
        self.jp_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.jp_name, 2, 2, 1, 1)
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setMaximumSize(QtCore.QSize(300, 16777215))
        self.image.setPixmap(QtGui.QPixmap(".\\../models/1.jpg"))
        self.image.setScaledContents(True)
        self.gridLayout.addWidget(self.image, 0, 0, 4, 1)
        character_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(character_window)
        QtCore.QMetaObject.connectSlotsByName(character_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.en_name.setText(_translate("MainWindow", "en_name"))
        self.role.setText(_translate("MainWindow", "role_txt"))
        self.role_lbl.setText(_translate("MainWindow", "Role"))
        self.name.setText(_translate("MainWindow", "name_txt"))
        self.name_lbl.setText(_translate("MainWindow", "Name"))
        self.en_voice_actor.setText(_translate("MainWindow", "EN Voice Actor"))
        self.jp_voice_actor.setText(_translate("MainWindow", "JP Voice Actor"))
        self.jp_name.setText(_translate("MainWindow", "jp_name"))

