from PyQt5 import QtCore, QtGui, QtWidgets


class EpisodeWindow(object):
    def main_ui(self, episode_window):
        episode_window.resize(640, 532)
        self.centralwidget = QtWidgets.QWidget(episode_window)
        self.centralwidget.setStyleSheet("background-color: rgb(52, 52, 52)")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.recap = QtWidgets.QLabel(self.centralwidget)
        self.recap.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.recap, 5, 0, 1, 1)
        self.recap_data = QtWidgets.QLabel(self.centralwidget)
        self.recap_data.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.recap_data, 5, 1, 1, 1)
        self.filler = QtWidgets.QLabel(self.centralwidget)
        self.filler.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.filler, 4, 0, 1, 1)
        self.en_title = QtWidgets.QLabel(self.centralwidget)
        self.en_title.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.en_title, 0, 0, 1, 1)
        self.watch_ru = QtWidgets.QPushButton(self.centralwidget)
        self.watch_ru.setMinimumSize(QtCore.QSize(0, 50))
        self.watch_ru.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\"; background-color: rgb(27, 27, 45);")
        self.gridLayout.addWidget(self.watch_ru, 6, 1, 1, 1)
        self.aired_date = QtWidgets.QLabel(self.centralwidget)
        self.aired_date.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.aired_date.setWordWrap(True)
        self.gridLayout.addWidget(self.aired_date, 3, 1, 1, 1)
        self.duration = QtWidgets.QLabel(self.centralwidget)
        self.duration.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.duration, 2, 0, 1, 1)
        self.filler_data = QtWidgets.QLabel(self.centralwidget)
        self.filler_data.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.filler_data, 4, 1, 1, 1)
        self.duration_time = QtWidgets.QLabel(self.centralwidget)
        self.duration_time.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.duration_time.setWordWrap(True)
        self.gridLayout.addWidget(self.duration_time, 2, 1, 1, 1)
        self.en_title_name = QtWidgets.QLabel(self.centralwidget)
        self.en_title_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.en_title_name.setWordWrap(True)
        self.gridLayout.addWidget(self.en_title_name, 0, 1, 1, 1)
        self.aired = QtWidgets.QLabel(self.centralwidget)
        self.aired.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.aired, 3, 0, 1, 1)
        self.jp_title_name = QtWidgets.QLabel(self.centralwidget)
        self.jp_title_name.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.jp_title_name.setWordWrap(True)
        self.gridLayout.addWidget(self.jp_title_name, 1, 1, 1, 1)
        self.jp_title = QtWidgets.QLabel(self.centralwidget)
        self.jp_title.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.gridLayout.addWidget(self.jp_title, 1, 0, 1, 1)
        self.watch_en = QtWidgets.QPushButton(self.centralwidget)
        self.watch_en.setMinimumSize(QtCore.QSize(0, 50))
        self.watch_en.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\"; background-color: rgb(27, 27, 45);")
        self.gridLayout.addWidget(self.watch_en, 6, 0, 1, 1)
        episode_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(episode_window)
        QtCore.QMetaObject.connectSlotsByName(episode_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.recap.setText(_translate("MainWindow", "Recap episode"))
        self.recap_data.setText(_translate("MainWindow", "recap"))
        self.filler.setText(_translate("MainWindow", "Filler episode"))
        self.en_title.setText(_translate("MainWindow", "Episode title"))
        self.watch_ru.setText(_translate("MainWindow", "Watch in Russian"))
        self.aired_date.setText(_translate("MainWindow", "aired_date"))
        self.duration.setText(_translate("MainWindow", "Duration"))
        self.filler_data.setText(_translate("MainWindow", "filler"))
        self.duration_time.setText(_translate("MainWindow", "duration"))
        self.en_title_name.setText(_translate("MainWindow", "title"))
        self.aired.setText(_translate("MainWindow", "Aired"))
        self.jp_title_name.setText(_translate("MainWindow", "jp_title"))
        self.jp_title.setText(_translate("MainWindow", "Japanese title"))
        self.watch_en.setText(_translate("MainWindow", "Watch in English"))


