from PyQt5 import QtCore, QtGui, QtWidgets
from login import *
from AnimeInfo import *


class MainPage(object):
    def __init__(self):
        self.logged_user = None
        self.logged_in = False

    def main_ui(self, MainWindow):
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.bg = QtWidgets.QFrame(self.centralwidget)
        self.bg.setEnabled(True)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1024, 720))
        self.bg.setStyleSheet("background-color: rgb(52, 52, 52)")
        self.bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.randomAnime = QtWidgets.QPushButton(self.bg)
        self.randomAnime.setGeometry(QtCore.QRect(370, 670, 291, 41))
        self.randomAnime.setStyleSheet(
            "color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.nextButton = QtWidgets.QPushButton(self.bg)
        self.nextButton.setGeometry(QtCore.QRect(870, 670, 141, 41))
        self.nextButton.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.myListButton = QtWidgets.QPushButton(self.bg)
        self.myListButton.setGeometry(QtCore.QRect(10, 10, 301, 51))
        self.myListButton.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.myListButton.hide()
        self.prevButton = QtWidgets.QPushButton(self.bg)
        self.prevButton.setGeometry(QtCore.QRect(10, 670, 141, 41))
        self.prevButton.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.loggedAs = QtWidgets.QLabel(self.bg)
        self.loggedAs.setGeometry(QtCore.QRect(740, 10, 151, 41))
        self.loggedAs.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.loggedAs.hide()
        self.loginButton = QtWidgets.QPushButton(self.bg)
        self.loginButton.setGeometry(QtCore.QRect(900, 10, 111, 51))
        self.loginButton.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\"; background-color: rgb(27, 27, 45);")
        self.Anime1 = QtWidgets.QFrame(self.bg)
        self.Anime1.setEnabled(True)
        self.Anime1.setGeometry(QtCore.QRect(10, 70, 1001, 191))
        self.Anime1.setStyleSheet("background-color: rgb(27, 27, 45)")
        self.Anime1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Anime1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AnimeButton1 = QtWidgets.QPushButton(self.Anime1)
        self.AnimeButton1.setGeometry(QtCore.QRect(0, 0, 1001, 191))
        self.AnimeButton1.setStyleSheet("opacity: 0; border: 0;")
        self.AnimeName1 = QtWidgets.QLabel(self.Anime1)
        self.AnimeName1.setGeometry(QtCore.QRect(190, 0, 811, 51))
        self.AnimeName1.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.AnimeName1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.AnimeSynopsis1 = QtWidgets.QLabel(self.Anime1)
        self.AnimeSynopsis1.setGeometry(QtCore.QRect(190, 50, 811, 141))
        self.AnimeSynopsis1.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.AnimeSynopsis1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.AnimeImage1 = QtWidgets.QLabel(self.Anime1)
        self.AnimeImage1.setEnabled(True)
        self.AnimeImage1.setGeometry(QtCore.QRect(0, 0, 191, 191))
        self.AnimeImage1.setPixmap(QtGui.QPixmap("../models/1.jpg"))
        self.AnimeImage1.setScaledContents(True)
        self.Anime2 = QtWidgets.QFrame(self.bg)
        self.Anime2.setEnabled(True)
        self.Anime2.setGeometry(QtCore.QRect(10, 270, 1001, 191))
        self.Anime2.setStyleSheet("background-color: rgb(27, 27, 45)")
        self.Anime2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Anime2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AnimeName2 = QtWidgets.QLabel(self.Anime2)
        self.AnimeName2.setGeometry(QtCore.QRect(190, 0, 811, 51))
        self.AnimeName2.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.AnimeName2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.AnimeSynopsis2 = QtWidgets.QLabel(self.Anime2)
        self.AnimeSynopsis2.setGeometry(QtCore.QRect(190, 50, 811, 141))
        self.AnimeSynopsis2.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.AnimeSynopsis2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.AnimeImage2 = QtWidgets.QLabel(self.Anime2)
        self.AnimeImage2.setEnabled(True)
        self.AnimeImage2.setGeometry(QtCore.QRect(0, 0, 191, 191))
        self.AnimeImage2.setPixmap(QtGui.QPixmap("../models/1.jpg"))
        self.AnimeImage2.setScaledContents(True)
        self.AnimeButton2 = QtWidgets.QPushButton(self.Anime2)
        self.AnimeButton2.setGeometry(QtCore.QRect(0, 0, 1001, 191))
        self.AnimeButton2.setStyleSheet("opacity: 0; border: 0;")
        self.Anime3 = QtWidgets.QFrame(self.bg)
        self.Anime3.setEnabled(True)
        self.Anime3.setGeometry(QtCore.QRect(10, 470, 1001, 191))
        self.Anime3.setStyleSheet("background-color: rgb(27, 27, 45)")
        self.Anime3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Anime3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AnimeButton3 = QtWidgets.QPushButton(self.Anime3)
        self.AnimeButton3.setGeometry(QtCore.QRect(0, 0, 1001, 191))
        self.AnimeButton3.setStyleSheet("opacity: 0; border: 0;")
        self.AnimeName3 = QtWidgets.QLabel(self.Anime3)
        self.AnimeName3.setGeometry(QtCore.QRect(190, 0, 811, 51))
        self.AnimeName3.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.AnimeName3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.AnimeSynopsis3 = QtWidgets.QLabel(self.Anime3)
        self.AnimeSynopsis3.setGeometry(QtCore.QRect(190, 50, 811, 141))
        self.AnimeSynopsis3.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";")
        self.AnimeSynopsis3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.AnimeImage3 = QtWidgets.QLabel(self.Anime3)
        self.AnimeImage3.setGeometry(QtCore.QRect(0, 0, 191, 191))
        self.AnimeImage3.setPixmap(QtGui.QPixmap("../models/1.jpg"))
        self.AnimeImage3.setScaledContents(True)
        self.switch_mode = QtWidgets.QPushButton(self.bg)
        self.switch_mode.setGeometry(QtCore.QRect(380, 10, 300, 51))
        self.switch_mode.setStyleSheet(u"color: rgb(255, 255, 255);\n"
                                           "font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        MainWindow.setCentralWidget(self.centralwidget)
        self.load_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.nextButton.clicked.connect(self.load_next_page)
        self.loginButton.clicked.connect(self.login)
        self.AnimeButton1.clicked.connect(self.anime_info)
        self.AnimeButton2.clicked.connect(self.anime_info)
        self.AnimeButton3.clicked.connect(self.anime_info)
        self.randomAnime.clicked.connect(self.anime_info)

    def load_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WeebApp"))
        self.randomAnime.setText(_translate("MainWindow", "Random Anime"))
        self.loggedAs.setText(_translate("MainWindow", f"Logged as {self.logged_user}"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.myListButton.setText(_translate("MainWindow", "My List"))
        self.prevButton.setText(_translate("MainWindow", "Prev"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.AnimeName1.setText(_translate("MainWindow", "TextLabel"))
        self.AnimeSynopsis1.setText(_translate("MainWindow", "TextLabel"))
        self.AnimeName2.setText(_translate("MainWindow", "TextLabel"))
        self.AnimeSynopsis2.setText(_translate("MainWindow", "TextLabel"))
        self.AnimeName3.setText(_translate("MainWindow", "TextLabel"))
        self.AnimeSynopsis3.setText(_translate("MainWindow", "TextLabel"))
        self.switch_mode.setText(_translate("MainWindow", "Switch to manga"))

    def load_next_page(self):
        # anime1, anime2, anime3 = get_anime_page()
        self.AnimeName1.setText('anime1.name')
        self.AnimeName2.setText('anime2.name')
        self.AnimeName3.setText('anime3.name')
        self.AnimeSynopsis1.setText('anime1.synospis')
        self.AnimeSynopsis2.setText('anime2.synospis')
        self.AnimeSynopsis3.setText('anime3.synospis')
        self.AnimeImage1.setPixmap(QtGui.QPixmap("../models/1.jpg"))
        self.AnimeImage2.setPixmap(QtGui.QPixmap("../models/2.jpg"))
        self.AnimeImage3.setPixmap(QtGui.QPixmap("../models/3.jpg"))

    def login(self):
        login_window = QtWidgets.QMainWindow()
        login_ui = LoginWindow(self)
        login_ui.main_ui(login_window)
        login_window.show()

    def anime_info(self):
        self.anime_info = QtWidgets.QMainWindow()
        self.anime_info_ui = AnimeInfo(self)
        self.anime_info_ui.main_ui(self.anime_info)
        self.anime_info.show()

    def logout(self):
        self.loggedAs.hide()
        self.myListButton.hide()
        self.logged_in = False
        self.loginButton.setText('Login')
        self.loginButton.clicked.connect(self.login)

    def logged_in_ui(self, username):
        self.logged_user = username
        self.loggedAs.show()
        self.myListButton.show()
        self.logged_in = True
        self.loggedAs.setText(f'Logged as {self.logged_user}')
        self.loginButton.setText('Logout')
        self.loginButton.clicked.disconnect(self.login)
        self.loginButton.clicked.connect(self.logout)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainPage()
    ui.main_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
