from PyQt5 import QtCore, QtGui, QtWidgets


class RegisterWindow(object):
    def main_ui(self, register_window):
        register_window.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(register_window)
        self.bg = QtWidgets.QFrame(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(-10, 0, 510, 510))
        self.bg.setStyleSheet("background-color: rgb(52, 52, 52)")
        self.bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_input = QtWidgets.QLineEdit(self.bg)
        self.login_input.setGeometry(QtCore.QRect(130, 130, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        self.login_input.setFont(font)
        self.pass_input = QtWidgets.QLineEdit(self.bg)
        self.pass_input.setGeometry(QtCore.QRect(130, 220, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        self.pass_input.setFont(font)
        self.pass_input.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.login_lbl = QtWidgets.QLabel(self.bg)
        self.login_lbl.setGeometry(QtCore.QRect(130, 100, 131, 31))
        self.login_lbl.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\"")
        self.pass_label = QtWidgets.QLabel(self.bg)
        self.pass_label.setGeometry(QtCore.QRect(130, 190, 131, 31))
        self.pass_label.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\"")
        self.create_btn_2 = QtWidgets.QPushButton(self.bg)
        self.create_btn_2.setGeometry(QtCore.QRect(270, 360, 130, 50))
        self.create_btn_2.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.cancel = QtWidgets.QPushButton(self.bg)
        self.cancel.setGeometry(QtCore.QRect(130, 360, 130, 50))
        self.cancel.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\";background-color: rgb(27, 27, 45)")
        self.error_lbl = QtWidgets.QLabel(self.bg)
        self.error_lbl.setGeometry(QtCore.QRect(130, 330, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        self.error_lbl.setFont(font)
        self.pass_input_2 = QtWidgets.QLineEdit(self.bg)
        self.pass_input_2.setGeometry(QtCore.QRect(130, 290, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        self.pass_input_2.setFont(font)
        self.pass_input_2.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.confirm_label = QtWidgets.QLabel(self.bg)
        self.confirm_label.setGeometry(QtCore.QRect(130, 260, 131, 31))
        self.confirm_label.setStyleSheet("color: rgb(255, 255, 255); font: 63 11pt \"Segoe UI Variable Display Semib\"")
        self.label = QtWidgets.QLabel(self.bg)
        self.label.setGeometry(QtCore.QRect(130, 40, 271, 61))
        self.label.setStyleSheet("color: rgb(255, 255, 255); font: 63 20pt \"Segoe UI Variable Display Semib\"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.cancel.clicked.connect(lambda: self.close_window(register_window))
        register_window.setCentralWidget(self.centralwidget)
        self.load_ui(register_window)
        QtCore.QMetaObject.connectSlotsByName(register_window)

    def load_ui(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_lbl.setText(_translate("MainWindow", "Login"))
        self.pass_label.setText(_translate("MainWindow", "Password"))
        self.create_btn_2.setText(_translate("MainWindow", "Create account"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.confirm_label.setText(_translate("MainWindow", "Confirm Password"))
        self.label.setText(_translate("MainWindow", "Registration"))

    def close_window(self, register_window):
        register_window.close()
